apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xbkyf9oop-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xbkyf9oop-go 
  name: xbkyf9oop-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xbkyf9oop-go 
